spring:
  mvc:
    format:
      date-time: iso
  application:
    name: serviceawards
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: hidden
            clientSecret: hidden
          google:
            client-id: hidden
            client-secret: hidden
server:
  port: 8088
---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 80
